/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;


import CapadeGestionDeBD.DetalleVenta_Reserva;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author javier
 */
public class PaneldePrenda extends javax.swing.JPanel implements ListCellRenderer<DetalleVenta_Reserva>{

    public PaneldePrenda() {
        initComponents();
    }
@Override
	public Component getListCellRendererComponent(JList<? extends DetalleVenta_Reserva> list,
			DetalleVenta_Reserva prenda, int index, boolean isSelected, boolean cellHasFocus) {
            talle.setText("Talle: "+prenda.getTalle());
            nombre.setText(prenda.getNombre());
            sexo.setText(" Sexo: Hombre");
            cantidad.setText(" Cantidad: "+prenda.getCantidad());
            //double total = prenda.getPrecio_producto()*prenda.getStock_producto();
            subtotal.setText("$ "+prenda.getSubtotal());
              
             byte[] bi = prenda.getImagen();
                   BufferedImage image = null;
                   InputStream in = new ByteArrayInputStream(bi);
                    
       try {
           image = ImageIO.read(in);
        } catch (IOException ex) {
            Logger.getLogger(PaneldePrenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon imgi = new ImageIcon(image.getScaledInstance(150, 150, 50));
        jLabel1.setIcon(imgi);
         this.repaint();
            return this;
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        talle = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        cantidad = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        nombre.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        nombre.setText("ADIDAS 10K");

        sexo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sexo.setText("sexo");

        talle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        talle.setText("talle");

        jToggleButton1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(204, 0, 0));
        jToggleButton1.setText("x");

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cantidad.setText("cantidad");

        subtotal.setFont(new java.awt.Font("Sitka Small", 0, 26)); // NOI18N
        subtotal.setText("$ 4555");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(jToggleButton1)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(talle, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(talle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel sexo;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel talle;
    // End of variables declaration//GEN-END:variables
}
